# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: Setup
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '= 3.0.4'

  - script: |
      gem install bundler
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'

- job: Checks
  steps:
  - script: bundle exec rake
    displayName: 'bundle exec rake'


- job: Containerize
  steps:
  - script: echo 'docker build'
    displayName: 'build docker image'
  - script: echo 'docker push'
    displayName: 'publish docker image'

- job: Deploy
  steps:
  - script: echo 'kat select'
    displayName: 'KAT select or create TEST'
